version: '2'
services:

  global_input_node:
    build: .
    image: dilshat/global_input_node
    container_name: global_input_node
    ports:
      - "1337:1337"
networks:
   default:
     external:
       name: iterativesolution_default
