version: '2'
services:

  node:    
    build: node
    image: dilshat/global_input_node
    container_name: global_input_node
    ports:
      - "1337:1337"    
networks:
   default:
     external:
       name: iterativesolution_default